spring:
  application:
    name: ReferralApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/dphone_referral
    username: postgres
    password: Finserv@2023
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  error:
    include-message: always
